### ISSUE TITLE
请问

### ISSUE THREAD

**Issue by shinianzhihou** [yeyupiaoling/PaddlePaddle-OCR#1]
你好，请问你这个是百度那个文字识别大赛的代码吗？

**Comment by yeyupiaoling** [comment]
@shinianzhihou 不是，这个我是参考PaddlePaddle下的Models的ocr模型自己改写的。

**Comment by shinianzhihou** [comment]
哦哦哦，我看你的id很像我在排行榜看到的那个第一大佬~想请教一下来着~-------- 原始邮件 --------发件人： 夜雨飘零 <notifications@github.com>日期： 2020年4月10日周五 下午3:05收件人： yeyupiaoling/PaddlePaddle-OCR <PaddlePaddle-OCR@noreply.github.com>抄送： Nian Shi <15155297566@163.com>, Mention <mention@noreply.github.com>主    题： Re: [yeyupiaoling/PaddlePaddle-OCR] 请问 (#1)

@shinianzhihou 不是，这个我是参考PaddlePaddle下的Models的ocr模型自己改写的。
